name: Post Publish
on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        description: 'Semver release tag e.g. v1.1.0'
        required: true
  workflow_run:
    workflows: [Release]
    types:
      - completed
jobs:
  on-success-or-workflow-dispatch:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    outputs:
      release-tag: ${{ steps.release-tag.outputs.release_tag }}
    steps:
      - if: github.event_name == 'workflow_run'
        name: Download Artifact from Release workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: release.yml
          name: release_tag
      - name: Output Release Tag
        id: release-tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo ::set-output name=release_tag::${{ github.event.inputs.release_tag }}
          else
            value=`cat release_tag.data`
            echo ::set-output name=release_tag::$value
          fi
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
  organize:
    needs: [ on-success-or-workflow-dispatch ]
    runs-on: ubuntu-latest
    steps:
      - name: Output Tag
        run: "echo RELEASE_TAG: ${{ needs.on-success-or-workflow-dispatch.outputs.release-tag }}"
