name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  go-version:
    runs-on: macos-latest
    outputs:
      version: ${{ steps.go-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: go-version
        run: echo "::set-output name=version::$(cat ./.go-version)"
  release-notes:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Release Notes
        run: sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/# $(git describe --abbrev=0 --exclude="$(git describe --abbrev=0 --match='v*.*.*' --tags)" --match='v*.*.*' --tags | tr -d v)/q;p" CHANGELOG.md > release-notes.txt
      - uses: actions/upload-artifact@v2
        with:
          name: release-notes
          path: release-notes.txt
          retention-days: 1
  terraform-provider-release:
    needs: [go-version, release-notes]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Allow tag to be fetched when ref is a commit
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-version.outputs.version }}
      - name: Release Notes Download
        id: release-notes-download
        uses: actions/download-artifact@v2
        with:
          name: release-notes
          path: /tmp
      - name: goreleaser release (with release notes)
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --release-notes ${{ steps.release-notes-download.outputs.download-path }}/release-notes.txt --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
